name: PostgreSQL Service Test

on:
  push:
  pull_request:

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          for i in {1..30}; do
            if pg_isready -h localhost -U testuser; then
              echo "PostgreSQL is ready!"
              break
            else
              sleep 1
            fi
          done

      - name: Confirm PostgreSQL connection
        run: |
          PGPASSWORD=testpassword psql -h localhost -U testuser -d testdb -c '\conninfo'

