name: PostgreSQL Service Test

on:
  push:
  pull_request:

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          while ! nc -z localhost 5432; do
            sleep 1
          done
          echo "PostgreSQL is ready!"

      - name: Confirm PostgreSQL connection
        run: |
          PGPASSWORD=testpassword psql -h localhost -U testuser -d testdb -c '\conninfo'

